-- =============================================================================
-- 033_fix_academic_staff_autoincrement.sql
-- Fixes HTTP 500 in SaveAcademicServlet: "Field 'id' doesn't have a default value"
-- =============================================================================

USE e_appointment_fskm;

-- Ensure academic_staff.id is auto-generated by MySQL.
ALTER TABLE academic_staff
  MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
